/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 154a657a768125ec5c2710eb3cabf7ca)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	HONO_API: Fetcher /* hono-pickball */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
